############## Read input parameters
suppressPackageStartupMessages(library("optparse"))

option_list <- list(
  make_option(c("-g", "--ground_truth"), type="character", default=NULL, 
              help="RDS file path with the ground truth data generated by STEP3",
              metavar="string")
)

opt <- parse_args(OptionParser(option_list=option_list))

if(file.exists(opt$ground_truth)) {
  GT <- readRDS(opt$ground_truth)
} else {
  stop("Please, indicate a correct RDS file")
}

cat(colnames(GT$Dgt), file = "mutName.txt", sep = '\n')